### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by rafeautie** [dfahlander/typeson#19]
Node 12.4

```javascript
import arrayNonindexKeys from './array-nonindex-keys.js';
    ^^^^^^
    
    SyntaxError: Cannot use import statement outside a module
        at Module._compile (internal/modules/cjs/loader.js:891:18)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
        at Module.load (internal/modules/cjs/loader.js:811:32)
        at Function.Module._load (internal/modules/cjs/loader.js:723:14)
        at Module.require (internal/modules/cjs/loader.js:848:19)
        at require (internal/modules/cjs/helpers.js:74:18)
        at Object.<anonymous> (/Users/hackreactor/Development/real-code/server/vm/TSON.js:7:5)
        at Module._compile (internal/modules/cjs/loader.js:955:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
        at Module.load (internal/modules/cjs/loader.js:811:32)
```

**Comment by rafeautie** [comment]
Didn't read the docs lol

**Comment by MitrovicMilosApp** [comment]
> Didn't read the docs lol

Same issue here. I'm just starting with backend development, so I believe that this is something simple that I have missed, but could you point out what it is?

**Comment by MitrovicMilosApp** [comment]
Thanks for the super quick response!

I am trying to do the import just as I have done on the existing projects, but since I created this one from scratch, something must have slipped 

v12.14.1

Hope that these images have enough info

<img width="726" alt="Screen Shot 2020-05-07 at 5 09 05 PM" src="https://user-images.githubusercontent.com/43935734/81311332-8da9ff80-9085-11ea-900d-71d226c2d60c.png">
<img width="659" alt="Screen Shot 2020-05-07 at 5 11 47 PM" src="https://user-images.githubusercontent.com/43935734/81311574-deb9f380-9085-11ea-9971-bdac80ea51fd.png">

**Comment by brettz9** [comment]
While it seems you are on Node 12 which does support ES Modules (ESM), which allows you to use `import` as you are doing (instead of `require`), if you wish to use bona fide modules, you need to use the file extension ".mjs" OR you need to put `"type": "module"` in your `package.json`.

If you have further questions, please ask on StackOverflow or such as this is not really related to typeson.

**Comment by MitrovicMilosApp** [comment]
Thanks for the answer!

Sorry, didn't think it through, it really is not the place for this
subject. I'll delete these comments

best regards!

чет, 7. мај 2020. у 17:20 Brett Zamir <notifications@github.com> је
написао/ла:
